on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy WeatherV2
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

    - name: Use Node.js 22
      uses: actions/setup-node@v2
      with:
        node-version: '22.12.0'
      
    - name: 🔨 Build Project
      run: |
        npm install
        npm run build

      env:
        VITE_OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: dist/
        server-dir: /
